# Generated by Django 5.2.1 on 2025-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("deadline", models.DateTimeField()),
                ("telegram_user_id", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("undone", "Undone"), ("done", "Done")],
                        default="undone",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
