# Generated by Django 5.2.1 on 2025-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notificated",
            field=models.BooleanField(default=False),
        ),
    ]
