# Generated by Django 5.2.1 on 2025-05-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_task_notificated"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user_timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
