# Generated by Django 5.2.1 on 2025-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_task_user_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="notificated",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user_timezone",
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.CharField(max_length=50),
        ),
    ]
