services:
  postgresql:
    image: postgres:latest
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - docker-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data


  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    environment:
      REDIS_PASSWORD: ${REDIS_PASS}
    command: redis-server --requirepass ${REDIS_PASS}
    networks:
      - docker-network
    volumes:
      - redis-data:/data




networks:
  docker-network:


volumes:
  postgresql-data:
  redis-data: